export enum AdminFuelStationContextLoadingEvent {
  GET_FUEL_STATION = 'GET_FUEL_STATION',
  GET_ASSIGNED_MANAGERS = 'GET_ASSIGNED_MANAGERS',
  GET_FUEL_ORDERS = 'GET_FUEL_ORDERS',
  ASSIGN_MANAGER = 'ASSIGN_MANAGER',
  UNASSIGN_MANAGER = 'UNASSIGN_MANAGER',
  CONFIRM_FUEL_ORDER = 'CONFIRM_FUEL_ORDER',
  REJECT_FUEL_ORDER = 'REJECT_FUEL_ORDER',
  CHANGE_FUEL_PRICE = 'CHANGE_FUEL_PRICE',
  DEACTIVATE_FUEL_STATION = 'DEACTIVATE_FUEL_STATION'
}