export enum ManagerFuelStationContextLoadingEvent {
  GET_FUEL_STATION = 'GET_FUEL_STATION',
  GET_ASSIGNED_MANAGERS = 'GET_ASSIGNED_MANAGERS',
  GET_FUEL_ORDERS = 'GET_FUEL_ORDERS',
  CREATE_FUEL_ORDER = 'CREATE_FUEL_ORDER'
}