
version: '3.8'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angular-app
    ports:
      - "80:80"
    restart: unless-stopped
    # If you need environment variables
    # environment:
    #   - API_URL=http://api-server:8080
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf