-- liquibase formatted sql

-- changeset oleksandr-chumak:001-create-user-table
CREATE TABLE user_roles
(
    user_role_id int8 PRIMARY KEY,
    role_name    varchar(50) NOT NULL
);
INSERT INTO user_roles
VALUES (1, 'administrator'),
       (2, 'manager');

CREATE TABLE user_statuses
(
    user_status_id int8 PRIMARY KEY,
    status_name    varchar(50) NOT NULL
);
INSERT INTO user_statuses
VALUES (1, 'active'),
       (2, 'terminated');


CREATE TABLE users
(
    user_id        int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name     varchar(100) NOT NULL,
    last_name      varchar(100) NOT NULL,
    full_name      varchar(255) NOT NULL,
    email          varchar(255) NOT NULL,
    password       varchar(255) NOT NULL,
    user_role_id   int8         NOT NULL,
    user_status_id int8         NOT NULL,
    CONSTRAINT users_user_role_id_fk FOREIGN KEY (user_role_id) REFERENCES user_roles (user_role_id),
    CONSTRAINT users_user_status_id_fk FOREIGN KEY (user_status_id) REFERENCES user_statuses (user_status_id)
);
