-- liquibase formatted sql

-- changeset oleksandr-chumak:001-create-credentials-table
CREATE TABLE credentials
(
    credentials_id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email          varchar(255) NOT NULL,
    password       varchar(255) NOT NULL,
    role           varchar(50)  NOT NULL,
    username       varchar(255) NOT NULL,
    CONSTRAINT credentials_username_uk UNIQUE (username),
    CONSTRAINT credentials_role_ck CHECK (role IN ('MANAGER', 'ADMINISTRATOR'))
);
