-- liquibase formatted sql

-- changeset oleksandr-chumak:001-create-credentials-table
CREATE TABLE user_roles
(
    user_role_id int8 PRIMARY KEY,
    role_name    varchar(50) NOT NULL
);
INSERT INTO user_roles
VALUES (1, 'administrator'),
       (2, 'manager');

CREATE TABLE credentials
(
    credentials_id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email          varchar(255) NOT NULL,
    password       varchar(255) NOT NULL,
    user_role_id   int8         NOT NULL,
    username       varchar(255) NOT NULL,
    CONSTRAINT credentials_username_uk UNIQUE (username),
    CONSTRAINT credentials_role_fk FOREIGN KEY (user_role_id) REFERENCES user_roles (user_role_id)
);
