-- liquibase formatted sql

-- changeset oleksandr-chumak:010-create-fuel-tax-rules-table
CREATE TABLE fuel_tax_rules
(
    tax_rule_id    int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_code   varchar(2)               NOT NULL,
    fuel_grade_id  int8                     NOT NULL,
    tax_type       varchar(50)              NOT NULL,
    name_local     varchar(100)             NOT NULL,
    name_english   varchar(100)             NOT NULL,
    description    text                     NOT NULL,
    value_type     varchar(20)              NOT NULL,
    amount         numeric(19, 6)           NOT NULL,
    currency       varchar(8)               NULL,
    unit           varchar(50)              NULL,
    effective_from TIMESTAMP WITH TIME ZONE NOT NULL,
    effective_to   TIMESTAMP WITH TIME ZONE NULL,
    CONSTRAINT fuel_tax_rules_fuel_grade_fk FOREIGN KEY (fuel_grade_id) REFERENCES fuel_grades (fuel_grade_id),
    CONSTRAINT fuel_tax_rules_value_type_check
        CHECK (value_type IN ('FIXED_AMOUNT', 'PERCENTAGE')),
    CONSTRAINT fuel_tax_rules_fixed_amount_check
        CHECK (
            (value_type = 'FIXED_AMOUNT' AND currency IS NOT NULL AND unit IS NOT NULL)
                OR
            (value_type = 'PERCENTAGE' AND currency IS NULL AND unit IS NULL)
            )
);
CREATE INDEX idx_fuel_tax_rules_country_grade_type_eff
    ON fuel_tax_rules (country_code, fuel_grade_id, tax_type, effective_from);
CREATE INDEX idx_fuel_tax_rules_eff_period
    ON fuel_tax_rules (effective_from, effective_to);

-- ============================================================================
-- GERMANY (DE)
-- ============================================================================

-- Energiesteuer on petrol RON 95 — €0.6545/L (standard) / €0.5141/L (reduced May-June 2026)
INSERT INTO fuel_tax_rules (country_code, fuel_grade_id, tax_type, name_local, name_english, description, value_type, amount,
                       currency, unit, effective_from, effective_to)
VALUES ('DE', 2, 'EXCISE', 'Energiesteuer', 'Energy Tax',
        'Federal excise duty on motor fuels under the German Energy Tax Act (Energiesteuergesetz). Levied per liter when fuel is removed from the tax warehouse, before VAT is calculated.',
        'FIXED_AMOUNT', 0.654500, 'EUR', 'PER_LITER', '2026-01-01 00:00:00+00', '2026-04-30 23:59:59+00'),

       ('DE', 2, 'EXCISE', 'Energiesteuer (reduziert)', 'Energy Tax (Reduced)',
        'Temporarily reduced energy tax under the Second Energy Tax Reduction Act (2. Energiesteuersenkungsgesetz), effective May 1 to June 30, 2026. Reduction of 14.04 cents per liter introduced as emergency relief during the Iran war fuel crisis.',
        'FIXED_AMOUNT', 0.514100, 'EUR', 'PER_LITER', '2026-05-01 00:00:00+00', '2026-06-30 23:59:59+00'),

       ('DE', 2, 'EXCISE', 'Energiesteuer', 'Energy Tax',
        'Federal excise duty on motor fuels under the German Energy Tax Act (Energiesteuergesetz). Returns to standard rate after temporary reduction expires.',
        'FIXED_AMOUNT', 0.654500, 'EUR', 'PER_LITER', '2026-07-01 00:00:00+00', NULL);

-- Energiesteuer on diesel — €0.4704/L (standard) / €0.3300/L (reduced)
INSERT INTO fuel_tax_rules (country_code, fuel_grade_id, tax_type, name_local, name_english, description, value_type, amount,
                       currency, unit, effective_from, effective_to)
VALUES ('DE', 3, 'EXCISE', 'Energiesteuer', 'Energy Tax',
        'Federal excise duty on diesel fuel under the German Energy Tax Act. Diesel is taxed at a lower rate than petrol due to historical EU policy favoring commercial transport.',
        'FIXED_AMOUNT', 0.470400, 'EUR', 'PER_LITER', '2026-01-01 00:00:00+00', '2026-04-30 23:59:59+00'),

       ('DE', 3, 'EXCISE', 'Energiesteuer (reduziert)', 'Energy Tax (Reduced)',
        'Temporarily reduced energy tax on diesel, effective May 1 to June 30, 2026. The 14.04 cent per liter reduction is based on the EU minimum tax rate under the Energy Tax Directive.',
        'FIXED_AMOUNT', 0.330000, 'EUR', 'PER_LITER', '2026-05-01 00:00:00+00', '2026-06-30 23:59:59+00'),

       ('DE', 3, 'EXCISE', 'Energiesteuer', 'Energy Tax',
        'Federal excise duty on diesel fuel under the German Energy Tax Act. Returns to standard rate after temporary reduction expires.',
        'FIXED_AMOUNT', 0.470400, 'EUR', 'PER_LITER', '2026-07-01 00:00:00+00', NULL);

-- CO2-Abgabe (national carbon levy via emissions trading)
INSERT INTO fuel_tax_rules (country_code, fuel_grade_id, tax_type, name_local, name_english, description, value_type, amount,
                       currency, unit, effective_from, effective_to)
VALUES ('DE', 2, 'CO2_LEVY', 'CO2-Abgabe', 'CO2 Levy',
        'National carbon pricing on fossil fuels under the German Fuel Emissions Trading Act (BEHG). From January 2026, prices are determined by an auction-based system with a price corridor of EUR 55-65 per tonne of CO2. Approximate impact: 17 cents per liter of petrol.',
        'FIXED_AMOUNT', 0.170000, 'EUR', 'PER_LITER', '2026-01-01 00:00:00+00', NULL),

       ('DE', 3, 'CO2_LEVY', 'CO2-Abgabe', 'CO2 Levy',
        'National carbon pricing on diesel under the German Fuel Emissions Trading Act (BEHG). Diesel has a higher CO2 emission factor per liter than petrol, resulting in a higher levy of approximately 19 cents per liter.',
        'FIXED_AMOUNT', 0.190000, 'EUR', 'PER_LITER', '2026-01-01 00:00:00+00', NULL);

-- Mehrwertsteuer (VAT) — 19%
INSERT INTO fuel_tax_rules (country_code, fuel_grade_id, tax_type, name_local, name_english, description, value_type, amount,
                       currency, unit, effective_from, effective_to)
VALUES ('DE', 2, 'VAT', 'Mehrwertsteuer', 'Value Added Tax',
        'Standard VAT rate applied to the full retail price including all excise duties and levies. Calculated as a percentage of the net price (wholesale + excise + CO2 levy + margin).',
        'PERCENTAGE', 19.000000, NULL, NULL, '2026-01-01 00:00:00+00', NULL),

       ('DE', 3, 'VAT', 'Mehrwertsteuer', 'Value Added Tax',
        'Standard VAT rate applied to the full retail price of diesel including all excise duties and levies.',
        'PERCENTAGE', 19.000000, NULL, NULL, '2026-01-01 00:00:00+00', NULL);

-- ============================================================================
-- NORWAY (NO)
-- ============================================================================

-- Veibruksavgift on petrol — 3.77 NOK/L (standard) / 0 NOK/L (Apr-Aug 2026 suspension)
INSERT INTO fuel_tax_rules (country_code, fuel_grade_id, tax_type, name_local, name_english, description, value_type, amount,
                       currency, unit, effective_from, effective_to)
VALUES ('NO', 2, 'EXCISE', 'Veibruksavgift', 'Road Usage Tax',
        'Norwegian road usage tax on petrol, levied per liter to fund road infrastructure and offset external costs of road traffic. Administered by the Norwegian Tax Administration (Skatteetaten).',
        'FIXED_AMOUNT', 3.770000, 'NOK', 'PER_LITER', '2026-01-01 00:00:00+00', '2026-03-31 23:59:59+00'),

       ('NO', 2, 'EXCISE', 'Veibruksavgift (suspendert)', 'Road Usage Tax (Suspended)',
        'Road usage tax temporarily set to zero from April 1 to August 31, 2026, as a relief measure for motorists during the period of high global fuel prices.',
        'FIXED_AMOUNT', 0.000000, 'NOK', 'PER_LITER', '2026-04-01 00:00:00+00', '2026-08-31 23:59:59+00'),

       ('NO', 2, 'EXCISE', 'Veibruksavgift', 'Road Usage Tax',
        'Norwegian road usage tax on petrol, returns to standard rate after the temporary suspension expires.',
        'FIXED_AMOUNT', 3.770000, 'NOK', 'PER_LITER', '2026-09-01 00:00:00+00', NULL);

-- Veibruksavgift on diesel — 2.28 NOK/L (lower rate due to commercial transport considerations)
INSERT INTO fuel_tax_rules (country_code, fuel_grade_id, tax_type, name_local, name_english, description, value_type, amount,
                       currency, unit, effective_from, effective_to)
VALUES ('NO', 3, 'EXCISE', 'Veibruksavgift', 'Road Usage Tax',
        'Norwegian road usage tax on diesel, levied per liter. Lower rate than petrol due to historical considerations for commercial freight transport.',
        'FIXED_AMOUNT', 2.280000, 'NOK', 'PER_LITER', '2026-01-01 00:00:00+00', '2026-03-31 23:59:59+00'),

       ('NO', 3, 'EXCISE', 'Veibruksavgift (suspendert)', 'Road Usage Tax (Suspended)',
        'Road usage tax on diesel temporarily set to zero from April 1 to August 31, 2026, as part of the same relief package applied to petrol.',
        'FIXED_AMOUNT', 0.000000, 'NOK', 'PER_LITER', '2026-04-01 00:00:00+00', '2026-08-31 23:59:59+00'),

       ('NO', 3, 'EXCISE', 'Veibruksavgift', 'Road Usage Tax',
        'Norwegian road usage tax on diesel, returns to standard rate after the temporary suspension expires.',
        'FIXED_AMOUNT', 2.280000, 'NOK', 'PER_LITER', '2026-09-01 00:00:00+00', NULL);

-- CO2-avgift (CO2 tax)
INSERT INTO fuel_tax_rules (country_code, fuel_grade_id, tax_type, name_local, name_english, description, value_type, amount,
                       currency, unit, effective_from, effective_to)
VALUES ('NO', 2, 'CO2_LEVY', 'CO2-avgift', 'CO2 Tax',
        'Norwegian CO2 tax on petrol, designed to incentivize lower-carbon transport. Norway has one of the highest carbon prices on transport fuels in Europe. Applied per liter based on CO2 emission factor of petrol.',
        'FIXED_AMOUNT', 3.800000, 'NOK', 'PER_LITER', '2026-01-01 00:00:00+00', NULL),

       ('NO', 3, 'CO2_LEVY', 'CO2-avgift', 'CO2 Tax',
        'Norwegian CO2 tax on diesel. Higher rate than petrol due to greater CO2 emissions per liter of diesel combustion. Together with road usage tax, makes up the bulk of taxes on Norwegian fuel.',
        'FIXED_AMOUNT', 4.420000, 'NOK', 'PER_LITER', '2026-01-01 00:00:00+00', NULL);

-- Merverdiavgift (VAT) — 25%
INSERT INTO fuel_tax_rules (country_code, fuel_grade_id, tax_type, name_local, name_english, description, value_type, amount,
                       currency, unit, effective_from, effective_to)
VALUES ('NO', 2, 'VAT', 'Merverdiavgift', 'Value Added Tax',
        'Standard Norwegian VAT rate applied to the full retail price of petrol. Norway has one of the highest VAT rates in Europe at 25%.',
        'PERCENTAGE', 25.000000, NULL, NULL, '2026-01-01 00:00:00+00', NULL),

       ('NO', 3, 'VAT', 'Merverdiavgift', 'Value Added Tax',
        'Standard Norwegian VAT rate applied to the full retail price of diesel including all excise duties and levies.',
        'PERCENTAGE', 25.000000, NULL, NULL, '2026-01-01 00:00:00+00', NULL);

-- ============================================================================
-- UKRAINE (UA)
-- ============================================================================

-- Excise on petrol RON 92 and RON 95 — EUR 300.8 / 1000 L
INSERT INTO fuel_tax_rules (country_code, fuel_grade_id, tax_type, name_local, name_english, description, value_type, amount,
                       currency, unit, effective_from, effective_to)
VALUES ('UA', 1, 'EXCISE', 'Акцизний податок', 'Excise Tax',
        'Ukrainian excise tax on petrol RON 92, denominated in EUR per 1000 liters as required by the Tax Code of Ukraine. Paid in UAH at the National Bank of Ukraine (NBU) exchange rate. Rate is increased annually as part of EU integration, targeting EUR 359/1000L by 2028.',
        'FIXED_AMOUNT', 300.800000, 'EUR', 'PER_1000_LITERS', '2026-01-01 00:00:00+00', '2026-12-31 23:59:59+00'),

       ('UA', 2, 'EXCISE', 'Акцизний податок', 'Excise Tax',
        'Ukrainian excise tax on petrol RON 95, denominated in EUR per 1000 liters. Same rate applies to all petrol grades. Increased from EUR 271.7 in 2025 to EUR 300.8 in 2026 as part of gradual harmonization with EU minimum tax rates under the EU Energy Tax Directive.',
        'FIXED_AMOUNT', 300.800000, 'EUR', 'PER_1000_LITERS', '2026-01-01 00:00:00+00', '2026-12-31 23:59:59+00');

-- Excise on diesel — EUR 253.8 / 1000 L
INSERT INTO fuel_tax_rules (country_code, fuel_grade_id, tax_type, name_local, name_english, description, value_type, amount,
                       currency, unit, effective_from, effective_to)
VALUES ('UA', 3, 'EXCISE', 'Акцизний податок', 'Excise Tax',
        'Ukrainian excise tax on diesel fuel (heavy distillates / gasoil group), denominated in EUR per 1000 liters. Increased from EUR 215.7 in 2025 to EUR 253.8 in 2026, with target rate of EUR 330/1000L by 2028.',
        'FIXED_AMOUNT', 253.800000, 'EUR', 'PER_1000_LITERS', '2026-01-01 00:00:00+00', '2026-12-31 23:59:59+00');

-- ПДВ (VAT) — 20%
INSERT INTO fuel_tax_rules (country_code, fuel_grade_id, tax_type, name_local, name_english, description, value_type, amount,
                       currency, unit, effective_from, effective_to)
VALUES ('UA', 1, 'VAT', 'ПДВ', 'Value Added Tax',
        'Ukrainian Value Added Tax (Податок на додану вартість) at standard rate of 20%, applied to the full retail price including excise tax. Calculated on the net price (wholesale + excise + retail margin).',
        'PERCENTAGE', 20.000000, NULL, NULL, '2026-01-01 00:00:00+00', NULL),

       ('UA', 2, 'VAT', 'ПДВ', 'Value Added Tax',
        'Ukrainian Value Added Tax at standard rate of 20%, applied to the full retail price of petrol RON 95 including all excise duties.',
        'PERCENTAGE', 20.000000, NULL, NULL, '2026-01-01 00:00:00+00', NULL),

       ('UA', 3, 'VAT', 'ПДВ', 'Value Added Tax',
        'Ukrainian Value Added Tax at standard rate of 20%, applied to the full retail price of diesel fuel.',
        'PERCENTAGE', 20.000000, NULL, NULL, '2026-01-01 00:00:00+00', NULL);