-- liquibase formatted sql

-- changeset oleksandr-chumak:0013-create-fuel-purchases-table
CREATE TABLE fuel_purchases (
    fuel_purchase_id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fuel_order_id    BIGINT        NOT NULL REFERENCES fuel_orders(fuel_order_id),
    fuel_station_id  BIGINT        NOT NULL REFERENCES fuel_stations(fuel_station_id),
    fuel_grade_id    int8          NOT NULL,
    amount           DECIMAL(10,2) NOT NULL,
    price_per_liter  DECIMAL(10,4) NOT NULL,
    currency         VARCHAR(8)    NOT NULL,
    total_price      DECIMAL(12,4) NOT NULL,
    purchased_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_fuel_purchases_station ON fuel_purchases (fuel_station_id, purchased_at DESC);
