-- liquibase formatted sql

-- changeset oleksandr-chumak:0014-create-fuel-station-fuel-price-history-table
CREATE TABLE fuel_station_fuel_price_history
(
    history_id      int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fuel_station_id int8                     NOT NULL,
    fuel_grade      varchar(50)              NOT NULL,
    price_per_liter numeric(10, 2)           NOT NULL,
    currency        varchar(8)               NOT NULL,
    changed_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    changed_by      int8,
    CONSTRAINT fsfph_station_fk FOREIGN KEY (fuel_station_id) REFERENCES fuel_stations (fuel_station_id) ON DELETE CASCADE,
    CONSTRAINT fsfph_actor_fk   FOREIGN KEY (changed_by) REFERENCES users (user_id)
);

CREATE INDEX ON fuel_station_fuel_price_history (fuel_station_id, changed_at DESC);
CREATE INDEX ON fuel_station_fuel_price_history (fuel_station_id, fuel_grade, changed_at DESC);
