-- liquibase formatted sql

-- changeset oleksandr-chumak:0018-create-fuel-tank-volume-history-table
CREATE TABLE fuel_tank_volume_history
(
    history_id      int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fuel_station_id int8                     NOT NULL,
    fuel_tank_id    int8                     NOT NULL,
    fuel_grade      varchar(50)              NOT NULL,
    old_volume      numeric(12, 3)           NOT NULL,
    new_volume      numeric(12, 3)           NOT NULL,
    reason          varchar(20)              NOT NULL,
    changed_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    changed_by      int8,
    CONSTRAINT ftvh_station_fk FOREIGN KEY (fuel_station_id) REFERENCES fuel_stations (fuel_station_id) ON DELETE CASCADE,
    CONSTRAINT ftvh_tank_fk    FOREIGN KEY (fuel_tank_id) REFERENCES fuel_station_fuel_tanks (fuel_tank_id) ON DELETE CASCADE,
    CONSTRAINT ftvh_actor_fk   FOREIGN KEY (changed_by) REFERENCES users (user_id)
);

CREATE INDEX ON fuel_tank_volume_history (fuel_station_id, changed_at DESC);
CREATE INDEX ON fuel_tank_volume_history (fuel_tank_id, changed_at DESC);
