-- liquibase formatted sql

-- changeset oleksandr-chumak:0019-create-fuel-sales-table
CREATE TABLE fuel_sales (
    fuel_sale_id     int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fuel_station_id  BIGINT        NOT NULL REFERENCES fuel_stations(fuel_station_id),
    fuel_tank_id     BIGINT        NOT NULL REFERENCES fuel_station_fuel_tanks(fuel_tank_id),
    fuel_grade_id    int8          NOT NULL,
    volume           DECIMAL(10,2) NOT NULL,
    price_per_liter  DECIMAL(10,4) NOT NULL,
    currency         VARCHAR(8)    NOT NULL,
    total_revenue    DECIMAL(12,4) NOT NULL,
    sold_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_fuel_sales_station ON fuel_sales (fuel_station_id, sold_at DESC);
CREATE INDEX idx_fuel_sales_tank    ON fuel_sales (fuel_tank_id, sold_at DESC);
