-- liquibase formatted sql

-- changeset oleksandr-chumak:004-create-fuel-stations-table
CREATE TABLE fuel_stations
(
    fuel_station_id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    building_number varchar(255)             NOT NULL,
    city            varchar(255)             NOT NULL,
    country         varchar(255)             NOT NULL,
    postal_code     varchar(255)             NOT NULL,
    street          varchar(255)             NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    status          varchar(50)              NOT NULL,
    CONSTRAINT fuel_stations_status_check CHECK (status IN ('ACTIVE', 'DEACTIVATED'))
);