-- liquibase formatted sql

-- changeset oleksandr-chumak:004-create-fuel-stations-table
CREATE TABLE fuel_station_statuses
(
    fuel_station_status_id int8 PRIMARY KEY,
    status_name            varchar(50) NOT NULL
);
INSERT INTO fuel_station_statuses
VALUES (1, 'active'),
       (2, 'deactivated');

CREATE TABLE fuel_grades
(
    fuel_grade_id   int8 PRIMARY KEY,
    fuel_grade_name varchar(50) NOT NULL
);
INSERT INTO fuel_grades
VALUES (1, 'ron-92'),
       (2, 'ron-95'),
       (3, 'diesel');

CREATE TABLE fuel_stations
(
    fuel_station_id        int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    building_number        varchar(255)             NOT NULL,
    city                   varchar(255)             NOT NULL,
    country                varchar(255)             NOT NULL,
    postal_code            varchar(255)             NOT NULL,
    street                 varchar(255)             NOT NULL,
    created_at             TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    fuel_station_status_id int8                     NOT NULL,
    CONSTRAINT fuel_stations_status_fk FOREIGN KEY (fuel_station_status_id) REFERENCES fuel_station_statuses (fuel_station_status_id)
);