-- liquibase formatted sql

-- changeset oleksandr-chumak:007-create-fuel-station-events-table
CREATE TABLE fuel_station_events
(
    event_id        int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fuel_station_id int8                     NOT NULL,
    event_type      varchar(100)             NOT NULL,
    occurred_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    performed_by    int8,
    payload         jsonb,
    CONSTRAINT fuel_station_events_station_fk FOREIGN KEY (fuel_station_id) REFERENCES fuel_stations (fuel_station_id) ON DELETE CASCADE,
    CONSTRAINT fuel_station_events_actor_fk FOREIGN KEY (performed_by) REFERENCES users (user_id)
);