-- liquibase formatted sql

-- changeset oleksandr-chumak:007-create-fuel-station-fuel-tanks-table
CREATE TABLE fuel_station_fuel_tanks
(
    fuel_tank_id     int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fuel_station_id  int8           NOT NULL,
    current_volume   numeric(12, 3) NOT NULL,
    fuel_grade_id    int8           NOT NULL,
    last_refill_date TIMESTAMP WITH TIME ZONE NULL,
    max_capacity     numeric(12, 3) NOT NULL,
    CONSTRAINT fuel_station_fuel_tanks_fuel_station_id_fk FOREIGN KEY (fuel_station_id) REFERENCES fuel_stations (fuel_station_id) ON DELETE CASCADE,
    CONSTRAINT fuel_station_fuel_tanks_fuel_grade_fk FOREIGN KEY (fuel_grade_id) REFERENCES fuel_grades (fuel_grade_id)
);