-- liquibase formatted sql

-- changeset oleksandr-chumak:008-create-fuel-orders-table
CREATE TABLE fuel_order_statuses
(
    fuel_order_status_id int8 PRIMARY KEY,
    status_name          varchar(50) NOT NULL
);
INSERT INTO fuel_order_statuses
VALUES (1, 'pending'),
       (2, 'confirmed'),
       (3, 'rejected'),
       (4, 'processed');

CREATE TABLE fuel_orders
(
    fuel_order_id        int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount               numeric(12, 3)           NOT NULL,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    fuel_station_id      int8                     NOT NULL,
    fuel_grade_id        int8                     NOT NULL,
    fuel_order_status_id int8                     NOT NULL,
    CONSTRAINT fuel_orders_fuel_station_id_fk FOREIGN KEY (fuel_station_id) REFERENCES fuel_stations (fuel_station_id) ON DELETE CASCADE,
    CONSTRAINT fuel_station_fuel_orders_fuel_grade_fk FOREIGN KEY (fuel_grade_id) REFERENCES fuel_grades (fuel_grade_id),
    CONSTRAINT fuel_orders_status_fk FOREIGN KEY (fuel_order_status_id) REFERENCES fuel_order_statuses (fuel_order_status_id)
);
CREATE INDEX ON fuel_orders (fuel_station_id);
CREATE INDEX ON fuel_orders (fuel_order_status_id);