-- liquibase formatted sql

-- changeset oleksandr-chumak:008-create-fuel-order-events-table
CREATE TABLE fuel_order_events
(
    event_id         int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fuel_order_id    int8                     NOT NULL,
    fuel_station_id  int8                     NOT NULL,
    event_type       varchar(100)             NOT NULL,
    occurred_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    performed_by     int8,
    payload          jsonb,
    CONSTRAINT fuel_order_events_order_fk FOREIGN KEY (fuel_order_id) REFERENCES fuel_orders (fuel_order_id) ON DELETE CASCADE,
    CONSTRAINT fuel_order_events_station_fk FOREIGN KEY (fuel_station_id) REFERENCES fuel_stations (fuel_station_id),
    CONSTRAINT fuel_order_events_actor_fk FOREIGN KEY (performed_by) REFERENCES users (user_id)
);
CREATE INDEX ON fuel_order_events (fuel_order_id, occurred_at DESC);
CREATE INDEX ON fuel_order_events (fuel_order_id, event_type, occurred_at DESC);
CREATE INDEX ON fuel_order_events (fuel_station_id, occurred_at DESC);
