-- liquibase formatted sql

-- changeset oleksandr-chumak:008-create-fuel-orders-table
CREATE TABLE fuel_orders
(
    fuel_order_id   int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount          numeric(12, 3)           NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    fuel_station_id int8                     NOT NULL,
    fuel_grade      varchar(50)              NOT NULL,
    status          varchar(50)              NOT NULL,
    CONSTRAINT fuel_orders_fuel_station_id_fk FOREIGN KEY (fuel_station_id) REFERENCES fuel_stations (fuel_station_id) ON DELETE CASCADE,
    CONSTRAINT fuel_station_fuel_orders_fuel_grade_check CHECK (fuel_grade IN ('RON_92', 'RON_95', 'DIESEL')),
    CONSTRAINT fuel_orders_status_check CHECK (status IN ('PENDING', 'CONFIRMED', 'REJECTED', 'PROCESSED'))
);
CREATE INDEX ON fuel_orders (fuel_station_id);
CREATE INDEX ON fuel_orders (status);