-- liquibase formatted sql

-- changeset oleksandr-chumak:009-create-fuel-prices-table
CREATE TABLE fuel_prices
(
    fuel_price_id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fuel_grade_id int8                     NOT NULL,
    price         numeric(19, 6)           NOT NULL,
    currency      varchar(8)               NOT NULL,
    unit          varchar(50)              NOT NULL,
    source        varchar(50)              NOT NULL,
    fetched_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT fuel_prices_fuel_grade_fk FOREIGN KEY (fuel_grade_id) REFERENCES fuel_grades (fuel_grade_id)
);
CREATE INDEX ON fuel_prices (fuel_grade_id, fetched_at DESC);
CREATE INDEX ON fuel_prices (source, fetched_at DESC);